name: worflow with github actions #opcional
on:
  push: #hace referencial a evento push (accion de subir codigo a github)
    branches:
      - main
      - dev
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: "install"
        run: npm run build
      - name: "test"
        run: npm install
      - name: "build"
        run: npm run test
      - name: "deploy"
        run: |
          npm install -g firebase-tools
          firebase deploy --token ${{ secrets.TOKEN }}
