name: worflow with github actions #opcional
on:
  push: #hace referencial a evento push (accion de subir codigo a github)
    branches:
      - main
      - dev
      - multiples-jobs
jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      with:
        node_version: "14"
        cache: 'npm'
      - run: npm install
      - run: npm test
        

  build:
    needs: [install_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      with:
        node_version: "14"
        cache: 'npm'
      - run: npm install  
      - run: npm run build
      - run: rm -r node_modules
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: .

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploy"
