name: worflow with github actions #opcional
on:
  push: #hace referencial a evento push (accion de subir codigo a github)
    branches:
      - main
      - dev
      - multiples-jobs
jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: install and test
        run: echo "install and test"

  build:
    needs: [install_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "build"

  deploy:
    needs: [install_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploy"
