name: workflow with github actions
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy_dev:
    if: ${{ github.ref == 'refs/heads/dev' }}
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/download-artifact@v2
        with:
          name: app
      - name: install firebase cli
        run: npm install -g firebase-tools
      - name: deploy
        run: ${{ secrets.TOKEN }}
