name: workflow with github actions
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy_dev:
    if: ${{ github.ref == 'refs/heads/dev' }}
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: ${{ secrets.TOKEN }}
